#!/bin/sh

cache=~/.cache/gdmenu_run

for i in $(echo $PATH | tr ':' ' ')
do
	if [ $i -nt $cache ]
	then
		shopt -s nullglob
		eval "echo {$(echo $PATH | tr ':' ',')}/*" | tr ' ' '\n' > $cache
		break
	fi
done

exec $(gdmenu -t 'Choose an Application' -m 10 < $cache)
